Updating Allrun script to automate the run, and remove unecessary cases

diff --git a/Diffuser/Allclean b/Diffuser/Allclean
--- a/Diffuser/Allclean
+++ b/Diffuser/Allclean
@@ -1,27 +1,50 @@
 #!/bin/sh
 cd "${0%/*}" || exit                                # Run from this directory
 
-. /OpenFOAM/OpenFOAM-v2412/etc/bashrc
+. /home/rokot/OpenFOAM/OpenFOAM-v2412/OpenFOAM-v2412/etc/bashrc
 
 . ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
 #------------------------------------------------------------------------------
 
 
 
-cases="SpalartAllmaras kOmegaSST kEpsilonPhitF  LaunderSharmaKE"
+#cases="SpalartAllmaras kOmegaSST kEpsilonPhitF  LaunderSharmaKE"
+
+keepCases="
+common
+"
+
+loseCases="
+SpalartAllmaras
+LaunderSharmaKE
+kOmegaSST
+kEpsilonPhitF
+"
+
+#for caseName in $keepCases
+#do
+#        ( cd "$caseName" && rm system/sample*[0-9]* && sed -i '/#includeFunc sample.*/d' system/controlDict && foamCleanTutorials)
+#done
+
+for caseName in $loseCases
+do
+    removeCase "$caseName"
+done
 
 
-for case in $cases; do
-    echo "Entering $case..."
-    cd "$case" || { echo "Failed to enter $case"; continue; }
+
+#for case in $cases; do
+#    echo "Entering $case..."
+#    cd "$case" || { echo "Failed to enter $case"; continue; }
    # rm -r 1* 2* 3* 4* 5* 6* 7* 8* 9*
    # wait
    # rm -r postProcessing
    # wait
-    foamCleanTutorials
+#    foamCleanTutorials
 #    rm -r ../Simulations/results/$case/postProcessing
-    cd ..
-done
+#    cd ..
+#done
+
 rm -r Figures
 rm support_Files/log.post
 
diff --git a/Diffuser/Allrun b/Diffuser/Allrun
--- a/Diffuser/Allrun
+++ b/Diffuser/Allrun
@@ -1,7 +1,7 @@
 #!/bin/sh
 cd "${0%/*}" || exit                                # Run from this directory
 
-. /OpenFOAM/OpenFOAM-v2412/etc/bashrc
+. /home/rokot/OpenFOAM/OpenFOAM-v2412/OpenFOAM-v2412/etc/bashrc
 
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
 #------------------------------------------------------------------------------
@@ -10,13 +10,45 @@ cd "${0%/*}" || exit                                # Run from this directory
 #wait
 #conda activate OFpy
 
-cases="SpalartAllmaras kOmegaSST kEpsilonPhitF  LaunderSharmaKE"
+selectModel()
+{
+    sed -i "s/modelName/$1/" "$1/constant/turbulenceProperties"
+}
+
+reduceTolerance()
+{
+    sed -i "s/relTol          0.1;/relTol          0.01;/" "$1/system/fvSolution"
+}
+
+decreaseRelaxation()
+{
+    sed -i 's/".*"            0.9/".*"            0.65/' "$1/system/fvSolution"
+}
+
+
+cases=" LaunderSharmaKE kEpsilonPhitF SpalartAllmaras kOmegaSST"
 
 mkdir Figures
-for case in $cases; do
-    echo "Entering $case..."
-    cd "$case" || { echo "Failed to enter $case"; continue; }
+for modelName in $cases; do
+        cloneCase common "$modelName"
+    case "$modelName" in
+    LaunderSharmaKE)
+       # decreaseRelaxation "$cases"
+        reduceTolerance "$modelName"
+        ;;
 
+    kEpsilonPhitF)
+        reduceTolerance "$modelName"
+        ;;
+
+    SpalartAllmaras)
+        decreaseRelaxation "$modelName"
+        ;;
+    esac
+    selectModel $modelName
+    echo "Entering $modelName..."
+    cd "$modelName" || { echo "Failed to enter $case"; continue; }
+    cp ../common/Diffuser.msh .
     # === Place your commands here ===
     # For example:
     cp -r 0.orig 0
